/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/structs.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Signal, Signal, AUTO)


PB_BIND(_Rectangle, _Rectangle, AUTO)


PB_BIND(_Color, _Color, AUTO)


PB_BIND(Rod, Rod, AUTO)


PB_BIND(RodGroup, RodGroup, 4)


PB_BIND(MousePosition, MousePosition, AUTO)


PB_BIND(InputState, InputState, AUTO)


PB_BIND(InputHistory, InputHistory, 2)









